#Development Profile (Eureka Disabled)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_dev
    username: root
    password: Skmania@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


# Disable Eureka Client for Development
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
 
# Disable Discovery Client
  cloud:
    discovery:
      enabled: false
    

    
jwt:
  secret: myVerySecretKeyForJwtAuthentication123456789
  expiration: 3600000