spring:
  application:
    name: employee-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # Default to dev
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

      
# Common configurations
server:
  port: 8081

      