package com.example.employee.service.config;

import java.io.IOException;
import java.io.InputStream;

import com.example.common.lib.exception.AddressServiceUnavailableException;
import com.example.common.lib.exception.BadRequestException;
import com.example.common.lib.exception.EmployeeServiceUnavailableException;
import com.example.common.lib.exception.ResourceNotFoundException;
import com.example.common.lib.response.ErrorResponse;
import com.fasterxml.jackson.databind.ObjectMapper;

import feign.Response;
import feign.codec.ErrorDecoder;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class CustomFeignErrorDecoder implements ErrorDecoder {

	private final ObjectMapper objectMapper;
	private final ErrorDecoder defaultDecoder = new ErrorDecoder.Default();

	public CustomFeignErrorDecoder(ObjectMapper objectMapper) {
		this.objectMapper = objectMapper;
	}

	@Override
	public Exception decode(String methodKey, Response response) {

		int status = response.status();
		
        /*
         * 503 can be generated by:
         * - Eureka / LoadBalancer
         * - connection failure
         * - remote service unavailable
         *
         * Therefore, don't try to parse its body as ErrorResponse.
         */
        if (status == 503) {

            log.error(
                    "Remote service unavailable - method: {}, status: {}",
                    methodKey,
                    status
            );

            return new AddressServiceUnavailableException(
                    "Address service is currently unavailable"
            );
        }

		// For normal downstream HTTP responses, try to read JSON
		
        /*
         * For normal HTTP error responses generated by
         * the downstream application, try to extract
         * our standard ErrorResponse message.
         */
        String message = extractMessage(response);

		log.error("Feign error - method: {}, status: {}, message: {}", methodKey, status, message);

		switch (status) {
		case 400:
			return new BadRequestException(message != null ? message : "Bad request to remote service");
		case 401:
			return new RuntimeException(message != null ? message : "Unauthorized request to remote service");
		case 403:
			return new RuntimeException(message != null ? message : "Forbidden request to remote service");
		case 404:
			return new ResourceNotFoundException(message != null ? message : "Requested resource not found");
		case 503:
			return new AddressServiceUnavailableException(
					message != null ? message : "Remote service is currently unavailable");
		default:
			return defaultDecoder.decode(methodKey, response);

		}

	}

	private String extractMessage(Response response) {

		if (response.body() == null) {
			return null;
		}

		String contentType = response.headers().getOrDefault("Content-Type", java.util.Collections.emptyList()).stream()
				.findFirst().orElse("");

		 /*
         * Only parse JSON responses.
         */
		if (!contentType.contains("application/json")) {
			log.warn("Feign error response is not JSON (content-type={}, status={}); skipping body parse", contentType,
					response.status());
			return null;
		}

		try (InputStream body = response.body().asInputStream()) {
			ErrorResponse error = objectMapper.readValue(body, ErrorResponse.class);
			return error.getMessage();
		} catch (IOException | RuntimeException ex) {

			log.warn("Unable to parse Feign error response. status={}, reason={}", response.status(), response.reason());
			return null;
		}
	}

}
