spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # Auth Service
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            # Employee Service
            - id: employee-service
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/employees/**


# Common configurations
server:
  port: 9090


# Eureka configuration
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:8761/eureka/

    healthcheck:
      enabled: true

    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 10

  instance:
    prefer-ip-address: true